
# pixels per cell
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

BUSH_ROWS = 2
BUSH_COLS = 3
BUSH_HEIGHT = BUSH_ROWS * CELL_SIZE
BUSH_WIDTH = BUSH_COLS * CELL_SIZE

WHITE=(200,200,200)
BLACK=(0,0,0)
GREEN = (0,100,0)
BLACK = (0, 0, 0)
WHITE = (200, 200, 200)
BACKGROUND_COLOR = GREEN

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

SOLDIER_HEIGHT = SOLDIER_ROWS * CELL_SIZE
SOLDIER_WIDTH = SOLDIER_COLS * CELL_SIZE

FLAG_ROWS = 3
FLAG_COLS = 4
FLAG_HEIGHT = FLAG_ROWS * CELL_SIZE
FLAG_WIDTH = FLAG_COLS * CELL_SIZE

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
MINE_HEIGHT = MINE_ROWS * CELL_SIZE
MINE_WIDTH = MINE_COLS * CELL_SIZE

# RUNNING_STATE = 1
# LOSE_STATE = 2
# WIN_STATE = 3

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
GAME_MASSAGE_COLOR = (89, 89, 89)
GAME_MASSAGE_TEXT = "Welcome to The Flag game.n\
Have Fun!"
GAME_MASSAGE_FONT_SIZE = 20
GAME_MASSAGE_LOCATION = (10, WINDOW_HEIGHT)