
CELL_SIZE = 20
# pixels per cell
BOARD_ROWS = 25
BOARD_COLS = 50
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE

BUSH_ROWS = 2
BUSH_COLS = 3
BUSH_HEIGHT = BUSH_ROWS * CELL_SIZE
BUSH_WIDTH = BUSH_COLS * CELL_SIZE

GREEN = (0,100,0)
BACKGROUND_COLOR = GREEN

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

FLAG_ROWS = 3
FLAG_COLS = 4

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3


RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3